PRMP 763 - New cron job lambda to update patient ods weekly
nhsconnect/national-document-repository-infrastructure pull request #187
Opened 2024-08-20 09:08 UTC by steph-torres-nhs

2024-08-20 09:40 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +module "update-patient-ods-lambda" {
Underscores please :)

2024-08-20 09:45 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +  depends_on = [
Can go because all are implicit.

2024-08-20 09:49 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +resource "aws_iam_policy" "dynamodb_policy_scan_lloyd_george" {
Remove `policy_` from name

2024-08-20 09:51 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +module "update-patient-ods-alarm" {
Underscores please :)

2024-08-20 09:52 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +module "update-patient-ods-alarm-topic" {
Underscores please :)

2024-08-20 09:52 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +  topic_name            = "update-patient-ods--topic"
`--`

2024-08-20 09:54 UTC, chrisbloe-nhse commented on infrastructure/schedules.tf
> +resource "aws_lambda_permission" "update_patient_ods_schedule_permission" {
Remove `_permission`

2024-08-20 09:54 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +
Remove extra new line, please :)

2024-08-21 08:10 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +          "dynamodb:Scan",
Best take the training comma off.

2024-08-21 08:10 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +          module.lloyd_george_reference_dynamodb_table.dynamodb_table_arn,
Best take the training comma off.

2024-08-21 08:12 UTC, chrisbloe-nhse commented on infrastructure/lambda-update-patient-ods.tf
> +          "SNS:Publish",
Best take the training comma off.

2024-08-21 10:15 UTC, chrisbloe-nhse requested changes
Thanks for making the suggested changes. The plan, whilst big, looks ok.

Does this need applying to all envs?

2024-08-27 10:18 UTC, chrisbloe-nhse approved these changes
The commas have been dropped, so this looks good now. Thanks :)

2024-08-27 13:14 UTC, NogaNHS commented on infrastructure/lambda-update-patient-ods.tf
> +    APPCONFIG_CONFIGURATION    = module.ndr-app-config.app_config_configuration_profile_id
Do we need this?

2024-08-27 13:15 UTC, NogaNHS commented on infrastructure/schedules.tf
> +resource "aws_cloudwatch_event_rule" "update_patient_ods_schedule" {
Maybe add a count on this, so it would only run on prod. I think we don't want this to run on dev every week.

2024-09-11 07:50 UTC, closed without merging