[PRPM-1284] Create NRL pointer, document upload
nhsconnect/national-document-repository-infrastructure pull request #226
Opened 2024-12-24 08:50 UTC by steph-torres-nhs

2025-01-07 13:43 UTC, NogaNHS commented on infrastructure/lambda-upload-confirm-result.tf
> +    module.sqs-nrl-queue.sqs_read_policy_document,
Does it need read?

2025-01-07 13:44 UTC, NogaNHS commented on infrastructure/lambda-upload-confirm-result.tf
> +    aws_iam_policy.ssm_access_policy.policy,
Why does it need ssm?

2025-01-09 09:18 UTC, abid-nhs commented on infrastructure/lambda-upload-confirm-result.tf
> +    aws_iam_policy.ssm_access_policy.policy,
could it be needed for this?
`APIM_API_URL = data.aws_ssm_parameter.apim_url.value`

2025-01-09 09:23 UTC, abid-nhs requested changes
Please review comments left by Noga

2025-01-10 14:08 UTC, steph-torres-nhs commented on infrastructure/lambda-upload-confirm-result.tf
> +    aws_iam_policy.ssm_access_policy.policy,
I took the same policies for the nrl queue as bulkupload but on second thought no it shouldn't need to read from the queue, should I also amend this in the bulkupload terraform?

2025-01-10 14:09 UTC, steph-torres-nhs commented on infrastructure/lambda-upload-confirm-result.tf
> +    module.sqs-nrl-queue.sqs_read_policy_document,
I took the same policies for the nrl queue as bulkupload but on second thought no it shouldn't need to read from the queue, should I also amend this in the bulkupload terraform?

2025-01-13 12:21 UTC, abid-nhs approved these changes

2025-01-17 13:49 UTC, merged